name: macOS Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  On-macOS:

    runs-on: macos-latest

    steps:
    - name: Try clang
      run: |
        which clang
        which make
        which brew
        which cc
        arch
        uname -a
