name: qemu Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  qemu:

    runs-on: ubuntu-latest

    steps:
    - uses: uraimo/run-on-arch-action@v2
      with:
        arch: aarch64
        distro: bullseye
        run: |
          which make
          which cc
          which gcc
