name: Windows Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  On-Windows:

    runs-on: windows-latest

    steps:
    - name: Try shell
      shell: gitbash.exe
      run: |
        pwd
        echo "haha"

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: 我在哪里？
      run: pwd

