name: Windows Build
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  On-Windows:

    runs-on: windows-2022

    steps:
    - name: Try shell
      shell: msys2 {0}
      run: |
        pwd
        which make
        echo "haha"
        pacman -S mingw-w64-ucrt-x86_64-gcc --noconfirm
        which make

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: 我在哪里？
      run: pwd

